package com.sample
 
import com.sample.Message;
import java.util.Map;
  




rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
       
        update( m );
end

rule "GoodBye" 
    when 
    	$config := Message(status == Message.GOODBYE,$km:10,$m:2220)  
        Message( status == Message.GOODBYE, myMessage : message,$config :=this)
   	 	 
    then 
        System.out.println($config+ myMessage+$km +$m);  
end


query subtest(Person $k) 
    accumulate($k := Person(age>20);$s:=sum($k.getAge()))
    eval($s > 1)
end

rule "GoodBye2"
  salience 9999
  no-loop 
    when    
    $p: Person()
       accumulate($p:= Person(name in ("ssaaaa","fff"));$total:sum($p.getAge()), $result_count : count(1))
    then 
        System.out.println("xxxxxxxxxxxxxxxxxxxx"+$total);  
end
